version: '3.7'

services:
  angular:
    build:
      context: ./Angular
    ports:
      - "4200:80"

  spring:
    restart: unless-stopped
    build:
      context: ./Spring
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - flask
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/smart_rh
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      FLASK_URL : http://flask:5000/flask
  flask:
    stop_signal: SIGINT
    build:
      context: ./Flask
    ports:
      - "5000:5000"

  postgres:
    restart: unless-stopped
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smart_rh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - angular
      - spring
      - flask
volumes:
  postgres_data: